'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Download,Plus,X,Shuffle,Check,ShieldCheck,Wallet,CalendarDays,Sparkles,AlertTriangle,FolderOpen} from 'lucide-react';
import {analyse,example,money,uid,sum,type Budget,type Item,type Log,surprises} from '../lib/budget';
import {parsePlan,savePlan,type SavedPlan} from '../lib/plan-file';

const steps=['Set up','First plan','Surprise','Revise','Reflect'];
const prettyDate=(value:string)=>value?new Date(value+'T12:00:00').toLocaleDateString('en-CA',{month:'short',day:'numeric'}):'Choose a date';
function Amount({label,value,onChange}:{label:string;value:number;onChange:(n:number)=>void}){
 return <label>{label}<span className="money-input"><span>$</span><input aria-label={label} type="number" min="0" max="10000000" step="0.01" value={value} onChange={e=>onChange(Math.min(10000000,Math.max(0,Number(e.target.value))))}/></span></label>;
}
function Confirm({title,children,onClose,onConfirm,action}:{title:string;children:ReactNode;onClose:()=>void;onConfirm:()=>void;action:string}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=ref.current;dialog?.showModal();return()=>dialog?.close()},[]);
 return <dialog ref={ref} onCancel={onClose} aria-labelledby="confirm-title"><h2 id="confirm-title">{title}</h2><p>{children}</p><div className="actions"><button className="secondary" autoFocus onClick={onClose}>Keep working</button><button className="primary" onClick={onConfirm}>{action}</button></div></dialog>;
}
function Entries({items,update,b,income=false}:{items:Item[];update:(items:Item[])=>void;b:Budget;income?:boolean}){
 return <div className="entries">{items.map(i=><div className="entry" key={i.id}>
 <label className="entry-name">{income?'Income name':'Item name'}<input aria-label={'Name for '+i.name} value={i.name} onChange={e=>update(items.map(x=>x.id===i.id?{...x,name:e.target.value}:x))}/></label>
 <label className="entry-date">{income?'Payday':'Due date'}<input aria-label={'Date for '+i.name} type="date" min={b.start} max={b.end} value={i.date} onChange={e=>update(items.map(x=>x.id===i.id?{...x,date:e.target.value}:x))}/></label>
 <Amount label={'Amount for '+i.name} value={i.amount} onChange={amount=>update(items.map(x=>x.id===i.id?{...x,amount}:x))}/>
 <button className="icon-button" aria-label={'Remove '+i.name} onClick={()=>update(items.filter(x=>x.id!==i.id))}><X size={20}/></button>
 </div>)}</div>;
}
function Income({b,onChange}:{b:Budget;onChange:(b:Budget)=>void}){
 return <div className="inset"><div className="section-title"><div><h3>Money coming in</h3><p>Enter what you take home, and when it arrives.</p></div><strong>{money(analyse(b).income)}</strong></div><Entries b={b} items={b.income} income update={income=>onChange({...b,income})}/><button className="text-button" onClick={()=>onChange({...b,income:[...b.income,{id:uid(),name:'New income',amount:0,date:b.start}]})}><Plus size={17}/>Add a payday or income</button></div>;
}
function Goal({b,onChange}:{b:Budget;onChange:(b:Budget)=>void}){
 const a=analyse(b),set=(v:Partial<Budget['goal']>)=>onChange({...b,goal:{...b.goal,...v}});
 return <section className="goal-box"><h3>Savings goal check</h3><p>What are you saving for, and by when?</p><div className="form-grid three"><label>What it’s for<input value={b.goal.name} onChange={e=>set({name:e.target.value})}/></label><Amount label="How much you need" value={b.goal.amount} onChange={amount=>set({amount})}/><label>Target date<input type="date" value={b.goal.target} onChange={e=>set({target:e.target.value})}/></label></div><div className="form-grid two"><Amount label="Already saved (separate from starting cash)" value={b.goal.saved} onChange={saved=>set({saved})}/><Amount label="Set aside each payday" value={b.goal.perPayday} onChange={perPayday=>set({perPayday})}/></div>
 {a.eligible.length?<p>To reach <strong>{money(b.goal.amount)}</strong> with {a.eligible.length} entered payday{a.eligible.length===1?'':'s'}, aim for <strong>{money(a.required)} per payday.</strong></p>:<p>Add a payday on or before your target to work out what to save.</p>}
 <button className="text-button" disabled={!a.eligible.length} onClick={()=>set({perPayday:a.required})}>Use suggested savings amount</button>
 {b.goal.target>b.end&&<p className="hint">Only paydays in this period count. Future pay isn’t assumed.</p>}</section>;
}
function Categories({b,onChange,original}:{b:Budget;onChange:(b:Budget)=>void;original?:Budget|null}){
 return <>{b.categories.map(c=>{const total=sum(c.items.filter(i=>i.date>=b.start&&i.date<=b.end));const old=original?.categories.find(x=>x.id===c.id);return <section className="inset category" key={c.id}><div className="section-title"><label className="category-label"><span className="sr-only">Category name</span><input aria-label={'Category name '+c.name} value={c.name} onChange={e=>onChange({...b,categories:b.categories.map(x=>x.id===c.id?{...x,name:e.target.value}:x)})}/></label><div className="category-total"><strong>{money(total)}</strong>{original&&<small>was {money(sum((old?.items||[]).filter(i=>i.date>=original.start&&i.date<=original.end)))}</small>}</div><button className="icon-button" aria-label={'Remove category '+c.name} onClick={()=>onChange({...b,categories:b.categories.filter(x=>x.id!==c.id)})}><X size={18}/></button></div><Entries b={b} items={c.items} update={items=>onChange({...b,categories:b.categories.map(x=>x.id===c.id?{...x,items}:x)})}/><button className="text-button" onClick={()=>onChange({...b,categories:b.categories.map(x=>x.id===c.id?{...x,items:[...x.items,{id:uid(),name:'New item',amount:0,date:b.start}]}:x)})}><Plus size={17}/>Add an item</button></section>})}
 <button className="secondary add-category" onClick={()=>onChange({...b,categories:[...b.categories,{id:uid(),name:'New category',items:[]}]})}><Plus size={18}/>Add a category</button></>;
}
function Totals({b}:{b:Budget}){const a=analyse(b);return <div className={'totals '+(a.left<0?'over':'')} aria-live="polite"><span>Money coming in: <strong>{money(a.income)}</strong></span><span>Planned expenses: <strong>{money(a.expenses)}</strong></span><span>Planned savings: <strong>{money(a.savings)}</strong></span><strong>Money left over: {money(a.left)}</strong><span>Starting cash included: <strong>{money(b.opening)}</strong></span><span>Total assigned: <strong>{money(a.expenses+a.savings)}</strong></span></div>}
function GoalStatus({b}:{b:Budget}){const a=analyse(b);return <div className="goal-box"><h3>Savings goal: {b.goal.name||'Your goal'} · {money(b.goal.amount)}</h3><p>Your plan sets aside <strong>{money(a.savings)}</strong> this period, plus {money(b.goal.saved)} already saved.</p><strong>{a.goalGap>0?`${money(a.goalGap)} still to go by ${prettyDate(b.goal.target)}.`:'Your entered plan covers this goal.'}</strong>{a.shortfall&&<p className="hint">Check the timeline too: setting money aside can leave a shortfall before payday.</p>}</div>}
function Timeline({b}:{b:Budget}){const a=analyse(b);return <section className="inset timeline"><div className="section-title"><h3>Payday timeline</h3><span>{a.paydays.length} payday date{a.paydays.length===1?'':'s'} this period</span></div><p>When money arrives and when each cost is due, in order.</p>{a.shortfall?<div className="warning"><AlertTriangle size={21}/><p>You run short on <strong>{prettyDate(a.shortfall.date)}</strong>: after {a.shortfall.name}, you’d be <strong>{money(Math.abs(a.shortfall.balance))} short</strong>{a.shortfall.nextPayday?` before payday on ${prettyDate(a.shortfall.nextPayday)}`:' with no later payday entered'}. Try changing an amount or a date.</p></div>:<div className="success"><Check size={19}/><span>Your entered plan stays at or above $0.</span></div>}
 <div className="timeline-head"><span>Date</span><span>What happens</span><span>In / out</span><span>Balance</span></div><div className="timeline-row starting"><time>{prettyDate(b.start)}</time><span>Starting cash</span><span>—</span><strong>{money(b.opening)}</strong></div>
 {a.timeline.map((t,i)=><div className={'timeline-row '+(t.balance<0?'short':'')+(t.type==='Payday'?' payday':'')} key={i}><time dateTime={t.date}>{prettyDate(t.date)}</time><span className="transaction-name">{t.type==='Payday'&&<Wallet size={16}/>} {t.name}<small>{t.type}</small></span><span className="transaction-amount">{t.type==='Payday'?'+':'−'}{money(t.amount)}</span><strong className="balance"><span className="sr-only">Balance </span>{money(t.balance)}</strong></div>)}
 <p className="hint">Same-day income arrives before expenses and savings. Lowest balance: {money(a.lowest)}.</p></section>}
function Comparison({original,b,chart=false}:{original:Budget;b:Budget;chart?:boolean}){
 const before=analyse(original),after=analyse(b);const ids=[...new Set([...original.categories.map(c=>c.id),...b.categories.map(c=>c.id)])];
 const rows=ids.map(id=>{const first=original.categories.find(c=>c.id===id),next=b.categories.find(c=>c.id===id);return {name:next?.name||first?.name||'Category',old:sum((first?.items||[]).filter(i=>i.date>=original.start&&i.date<=original.end)),now:sum((next?.items||[]).filter(i=>i.date>=b.start&&i.date<=b.end))}});rows.push({name:'Savings',old:before.savings,now:after.savings});const max=Math.max(1,...rows.flatMap(r=>[r.old,r.now]));
 return <div className="comparison"><h3>Before and after</h3>{chart&&<div className="legend"><span><i/>First plan</span><span><i/>Revised</span></div>}{rows.map((r,i)=><div className="comparison-row" key={i}><div><strong>{r.name}</strong><span>{money(r.old)} <span aria-hidden="true">→</span> <strong>{money(r.now)}</strong> <small>({r.now===r.old?'no change':money(Math.round((r.now-r.old)*100)/100)})</small></span></div>{chart&&<div className="bars" aria-hidden="true"><span style={{width:r.old/max*100+'%'}}/><span style={{width:r.now/max*100+'%'}}/></div>}</div>)}<div className="comparison-row final"><div><span>Money coming in</span><span>{money(before.income)} → <strong>{money(after.income)}</strong></span></div></div><div className="comparison-row"><div><strong>Money left over</strong><span>{money(before.left)} → <strong>{money(after.left)}</strong></span></div></div><div className="comparison-row"><div><span>Lowest cash balance</span><span>{money(before.lowest)} → <strong>{money(after.lowest)}</strong></span></div></div></div>;
}
export default function Home(){
 const [b,setB]=useState(()=>example('blank',new Date())),[original,setOriginal]=useState<Budget|null>(null),[step,setStep]=useState(0),[started,setStarted]=useState(false),[kind,setKind]=useState(''),[pendingKind,setPendingKind]=useState(''),[pendingPlan,setPendingPlan]=useState<SavedPlan|null>(null),[notice,setNotice]=useState(''),[events,setEvents]=useState<Log[]>([]),[trades,setTrades]=useState<Log[]>([]),[reflection,setReflection]=useState(''),[busy,setBusy]=useState(false),[drawn,setDrawn]=useState<number|null>(null),[eventType,setEventType]=useState('all'),[eventDate,setEventDate]=useState(''),[choice,setChoice]=useState('Concert ticket'),[cost,setCost]=useState(60),[choiceDate,setChoiceDate]=useState(''),[fund,setFund]=useState('buffer'),[lab,setLab]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null),stepHeading=useRef<HTMLHeadingElement>(null),firstRender=useRef(true);const a=analyse(b);
 useEffect(()=>{if(!started)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[started]);
 useEffect(()=>{if(firstRender.current){firstRender.current=false;return;}stepHeading.current?.focus();window.scrollTo({top:0,behavior:'instant'})},[step]);
 function go(n:number){if(!started&&n>0)return;if(n>=2&&!original)setOriginal(structuredClone(b));setStep(n);setNotice('');}
 function reset(k:string){const fresh=example(k,new Date());setB(fresh);setOriginal(null);setEvents([]);setTrades([]);setReflection('');setStarted(true);setKind(k);setPendingKind('');setDrawn(null);setFund('buffer');setChoiceDate(fresh.start);setEventDate(fresh.start);setStep(0);setNotice('');}
 function save(){try{savePlan({format:'tfc-budget-lab',version:1,budget:b,original,events,trades,reflection});setNotice('Plan file downloaded. Open it here next time to pick up where you left off.');}catch{setNotice('Check that every item has a valid date, then try saving again.');}}
 async function openFile(file?:File){if(!file)return;try{if(file.size>2000000)throw new Error();const plan=parsePlan(await file.text());if(started)setPendingPlan(plan);else restore(plan);}catch{setNotice('Choose a TFC plan JSON file (up to 2 MB). Your current plan has not changed.');}finally{if(fileInput.current)fileInput.current.value='';}}
 function restore(p:SavedPlan){setB(p.budget);setOriginal(p.original);setEvents(p.events);setTrades(p.trades);setReflection(p.reflection);setStarted(true);setKind('');setPendingPlan(null);setDrawn(null);setFund('buffer');setEventDate(p.budget.start);setChoiceDate(p.budget.start);setStep(p.original?3:1);setNotice('Welcome back. Your saved plan is ready.');}
 async function excel(){setBusy(true);try{const {exportBudget}=await import('../lib/export');await exportBudget(original||b,b,events,trades,reflection);setNotice('Excel downloaded. Use Save my plan as well if you want to edit it here later.');}catch{setNotice('The Excel download failed. Please try again.');}finally{setBusy(false)}}
 const validDate=(d:string)=>d>=b.start&&d<=b.end;
 function draw(type=eventType){setEventType(type);setLab(false);const candidates=surprises.map((s,i)=>({s,i})).filter(({s,i})=>(type==='cost'?s.amount<0:type==='income'?s.amount>0:true)&&i!==drawn);setDrawn(candidates[Math.floor(Math.random()*candidates.length)].i);}
 function eventPlan(index:number){const e=surprises[index],i={id:uid(),name:e.name,amount:Math.abs(e.amount),date:eventDate};return {...b,...(e.amount>0?{income:[...b.income,i]}:{categories:[...b.categories,{id:uid(),name:'Unexpected costs',items:[i]}]})};}
 const eventPreview=drawn===null?null:analyse(eventPlan(drawn));
 function applyEvent(){if(drawn===null||!validDate(eventDate))return;const e=surprises[drawn];setB(eventPlan(drawn));setEvents([...events,{...e,date:eventDate}]);setDrawn(null);setStep(3);setNotice('Surprise added. Change any amount or date to make the plan work for you.');}
 function choiceBudget(){const next=structuredClone(b);if(fund==='savings'){next.goal.perPayday=Math.max(0,next.goal.perPayday-(a.eligible.length?cost/a.eligible.length:0));}else if(fund!=='buffer'){let remaining=cost;next.categories.find(c=>c.id===fund)?.items.filter(i=>validDate(i.date)).forEach(i=>{const cut=Math.min(i.amount,remaining);i.amount=Math.round((i.amount-cut)*100)/100;remaining-=cut;});}next.categories.push({id:uid(),name:'Spending choices',items:[{id:uid(),name:choice||'Spending choice',amount:cost,date:choiceDate}]});return next;}
 const trial=analyse(choiceBudget()),nextPayday=trial.paydays.find(d=>d>choiceDate),interval=trial.timeline.filter(t=>t.date>=choiceDate&&(!nextPayday||t.date<nextPayday)),untilPayday=interval.length?Math.min(...interval.map(t=>t.balance)):trial.left;
 function applyChoice(){if(!validDate(choiceDate)||cost<=0)return;setB(choiceBudget());setTrades([...trades,{name:choice,amount:cost,date:choiceDate,detail:`Funding: ${fund==='buffer'?'Buffer':fund==='savings'?'Savings':b.categories.find(c=>c.id===fund)?.name}. Savings ${money(a.savings)} to ${money(trial.savings)}; expenses ${money(a.expenses)} to ${money(trial.expenses)}; buffer ${money(a.left)} to ${money(trial.left)}.`}]);setStep(3);setCost(0);setNotice('Choice added to your revised plan.');}
 const originalView=original||b;
 return <><header className="site-header"><div className="header-inner"><a className="brand" href="#main"><img src="/tfc-logo.png" alt="Teen Finance Club logo"/><span><strong>TFC Budget Lab</strong><small>Make a plan. Try a choice. See what changes.</small></span></a><div className="file-actions"><input hidden ref={fileInput} type="file" accept=".json,application/json" onChange={e=>openFile(e.target.files?.[0])}/><button className="secondary" onClick={()=>fileInput.current?.click()}><FolderOpen size={17}/><span>Open a plan</span></button>{started&&<button className="primary" onClick={save}><Download size={17}/><span>Save my plan</span></button>}</div></div></header>
 <main id="main"><section className="stepper" aria-label="Your progress"><h2 ref={stepHeading} tabIndex={-1} className="step-title">Step {step+1} of 5 · {steps[step]}</h2><nav aria-label="Budget steps">{steps.map((s,i)=><button key={s} disabled={!started&&i>0} aria-current={i===step?'step':undefined} className={i===step?'current':i<step?'complete':''} onClick={()=>go(i)}><span className="step-track"/><span>{i+1}. {s}</span></button>)}</nav></section>
 {notice&&<div className="notice" role="status"><span>{notice}</span><button className="icon-button" aria-label="Dismiss message" onClick={()=>setNotice('')}><X size={18}/></button></div>}
 {pendingKind&&<Confirm title="Start a fresh plan?" action="Start fresh" onClose={()=>setPendingKind('')} onConfirm={()=>reset(pendingKind)}>This replaces both plans and your reflection. Save your current plan first if you want to keep it.</Confirm>}
 {pendingPlan&&<Confirm title="Open this saved plan?" action="Open saved plan" onClose={()=>setPendingPlan(null)} onConfirm={()=>restore(pendingPlan)}>This replaces what is on screen. Save your current plan first if you want to keep both.</Confirm>}
 {a.excluded>0&&<div className="warning" role="alert"><AlertTriangle size={20}/><p>{a.excluded} item{a.excluded===1?' has':'s have'} missing or out-of-period dates. These items are excluded from totals. Update the dates in your plan.</p></div>}
 {step===0&&<><section className="hero"><img src="/tfc-logo.png" alt=""/><h1>TFC Budget Lab</h1><h2>Make a plan. Try a choice. See what changes.</h2><p>Your money, your choices. Make room for what matters to you.<br/>No account needed. Save your plan file to come back anytime.</p></section><section className="panel"><h2>Choose your starting point</h2><p className="lead">Start from an example you can edit, or type in your own numbers.</p><div className="starting-options">{[{id:'job',name:'Part-time job',detail:'A few café shifts. Two paydays to plan around.',value:'$640.00'},{id:'allowance',name:'Allowance',detail:'Regular money from family, with room for your priorities.',value:'$200.00'},{id:'blank',name:'My own numbers',detail:'Start fresh with your own income, costs, and goals.',value:'Your call'}].map(x=><button key={x.id} aria-pressed={kind===x.id} className={kind===x.id?'selected':''} onClick={()=>started?setPendingKind(x.id):reset(x.id)}><h3>{x.name}</h3><p>{x.detail}</p><strong>{x.value}{x.id!=='blank'&&<small> / period</small>}</strong></button>)}</div>
 {started?<><div className="form-grid three"><label>Period starts<input type="date" max={b.end} value={b.start} onChange={e=>e.target.value&&e.target.value<=b.end&&setB({...b,start:e.target.value})}/></label><label>Period ends<input type="date" min={b.start} value={b.end} onChange={e=>e.target.value&&e.target.value>=b.start&&setB({...b,end:e.target.value})}/></label><Amount label="Starting cash" value={b.opening} onChange={opening=>setB({...b,opening})}/></div><p className="hint">Starting cash is money you already have to spend. Existing goal savings are separate.</p><Income b={b} onChange={setB}/><Goal b={b} onChange={setB}/><div className="actions right"><button className="primary" onClick={()=>go(original?3:1)}>{original?'Continue my revised plan':'Build my plan'}</button></div></>:<p className="setup-hint"><ShieldCheck size={20}/>Choose a starting point above, or open a saved plan. Your budget stays in your browser tab.</p>}</section></>}
 {step===1&&<section className="panel"><h1>{original?'Your first plan':'Build your first plan'}</h1><p className="lead">Add, rename, or remove items, and set the day each one is due. Whatever you don’t assign stays as money left over.</p>{original&&<div className="success"><Check size={19}/><span>This is your original snapshot. Make new changes in <button className="inline-link" onClick={()=>go(3)}>Revise</button>.</span></div>}<fieldset disabled={!!original}><Categories b={originalView} onChange={setB}/>{!original&&<Goal b={b} onChange={setB}/>}</fieldset><Totals b={originalView}/><GoalStatus b={originalView}/><Timeline b={originalView}/><div className="actions"><button className="secondary" onClick={()=>go(0)}>Back</button><button className="primary" onClick={()=>go(2)}>{original?'Try a surprise':'Lock in my first plan'}</button></div></section>}
 {step===2&&<section className="panel"><h1>Something unexpected!</h1><p className="lead">Life doesn’t always follow the plan. Try a surprise, or test a spending choice.</p><div className="event-filters"><button className={!lab&&eventType==='all'?'primary':'secondary'} onClick={()=>draw('all')}><Shuffle size={18}/>Surprise me</button><button className={!lab&&eventType==='cost'?'primary':'secondary'} onClick={()=>draw('cost')}>Unexpected cost</button><button className={!lab&&eventType==='income'?'primary':'secondary'} onClick={()=>draw('income')}>Extra income</button><button className={lab?'primary':'secondary'} onClick={()=>{setLab(true);setDrawn(null)}}>Spending choice</button></div>
 {drawn!==null&&!lab&&<div className="event-card"><span className="badge">{surprises[drawn].amount<0?'Unexpected cost':'Extra income'}</span><h2>{surprises[drawn].name} · {surprises[drawn].amount>0?'+':'−'}{money(Math.abs(surprises[drawn].amount))}</h2><p>{surprises[drawn].detail}</p><label className="event-date">When does it happen?<input type="date" min={b.start} max={b.end} value={eventDate} onChange={e=>setEventDate(e.target.value)}/></label><div className="event-impact"><strong>What changes?</strong><p>Your buffer moves from {money(a.left)} to <strong>{money(eventPreview?.left??a.left)}</strong>.</p><p>Savings set aside: {money(eventPreview?.savings??a.savings)}. Lowest cash balance: <strong>{money(eventPreview?.lowest??a.lowest)}</strong>.</p>{surprises[drawn].amount>0&&<small>A new income date also counts as a payday for your savings plan.</small>}</div><button className="text-button" onClick={()=>draw()}>Try another surprise</button>{!validDate(eventDate)&&<p className="error-text">Choose a date within your period.</p>}</div>}
 {lab&&<div className="event-card choice-card"><span className="badge">A choice you can try</span><h2>Is it worth it to you?</h2><div className="form-grid three"><label>What are you thinking of buying?<input value={choice} onChange={e=>setChoice(e.target.value)}/></label><Amount label="Cost" value={cost} onChange={setCost}/><label>Spending date<input type="date" min={b.start} max={b.end} value={choiceDate} onChange={e=>setChoiceDate(e.target.value)}/></label></div><label>Where would the money come from?<select value={fund} onChange={e=>setFund(e.target.value)}><option value="buffer">My leftover buffer</option><option value="savings">Save less each payday</option>{b.categories.map(c=><option key={c.id} value={c.id}>Cut back: {c.name}</option>)}</select></label><div className="choice-impact" aria-live="polite"><strong>{choice||'This choice'} costs {money(cost)}.</strong><p>{untilPayday<0?`You could run ${money(Math.abs(untilPayday))} short`:`Your lowest planned balance would be ${money(untilPayday)}`} {nextPayday?`before your next payday on ${prettyDate(nextPayday)}.`:'before this period ends.'}</p><div className="form-grid two"><span>Savings: {money(a.savings)} → <strong>{money(trial.savings)}</strong></span><span>Buffer: {money(a.left)} → <strong>{money(trial.left)}</strong></span></div></div><p className="hint">{fund==='savings'?'Savings are reduced evenly across eligible paydays.':fund==='buffer'?'Your other expenses and savings stay the same.':'Items in the selected category are reduced in listed order, down to $0.'} Any uncovered cost comes from your buffer.</p>{!validDate(choiceDate)&&<p className="error-text">Choose a date within your period.</p>}</div>}
 {drawn===null&&!lab&&<div className="surprise-empty"><Sparkles size={32}/><p>A little extra cash. An unexpected bill.<br/>Pick an option above to see what changes.</p></div>}
 <p className="muted">Your current plan leaves <strong>{money(a.left)}</strong> unassigned.</p><div className="actions"><button className="secondary" onClick={()=>go(1)}>Back</button>{lab?<button className="primary" disabled={!validDate(choiceDate)||cost<=0} onClick={applyChoice}>Apply choice & revise</button>:drawn!==null?<button className="primary" disabled={!validDate(eventDate)} onClick={applyEvent}>Add surprise & revise</button>:<button className="primary" onClick={()=>go(3)}>Revise my plan</button>}</div></section>}
 {step===3&&<section className="panel"><h1>What would you change?</h1><p className="lead">Your first plan is kept for comparison. Change any item to make this period work for you.</p>{events.length>0&&<div className="event-recap">{events.map((e,i)=><p key={i}><strong>{e.name} ({prettyDate(e.date)}):</strong> {e.amount>0?'+':''}{money(e.amount)}</p>)}</div>}<Categories b={b} onChange={setB} original={original}/><details className="edit-income"><summary>Change my income or starting cash</summary><Amount label="Starting cash" value={b.opening} onChange={opening=>setB({...b,opening})}/><Income b={b} onChange={setB}/></details><Goal b={b} onChange={setB}/><Totals b={b}/>{original&&<Comparison original={original} b={b}/>}<Timeline b={b}/><div className="actions"><button className="secondary" onClick={()=>go(2)}>Back</button><button className="primary" onClick={()=>go(4)}>See my before & after</button></div></section>}
 {step===4&&<><section className="panel"><h1>Your before & after</h1><p className="lead">See what you moved, what you kept, and what that means for your money.</p>{events.length>0&&<div className="event-recap">{events.map((e,i)=><p key={i}><strong>{e.name}</strong> · {prettyDate(e.date)} · {money(e.amount)}</p>)}</div>}{original&&<Comparison original={original} b={b} chart/>}<GoalStatus b={b}/>{trades.length>0&&<div className="trade-log"><h3>Choices you tried</h3>{trades.map((t,i)=><p key={i}><strong>{t.name} · {prettyDate(t.date)}</strong><br/>{t.detail}</p>)}</div>}</section><section className="panel"><h2>Reflection</h2><div className="reflection-note"><strong>A plan can change with you.</strong><p>Making room for one thing can mean spending less on another. You get to decide what matters most.</p></div><label className="reflection-label">What did you change, and why?<textarea rows={5} value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="I changed… because…"/></label><p className="hint">No perfect answer needed. Your reflection goes into your plan file and spreadsheet.</p></section><section className="takeaway"><h2>Take it with you</h2><p>Save a plan file to keep editing here later, or download a spreadsheet with both budgets, dates, surprises, choices, and your reflection.</p><div className="download-actions"><button className="primary" onClick={save}><Download size={18}/>Save my plan</button><button className="secondary" onClick={excel} disabled={busy}>{busy?'Preparing spreadsheet…':'Download Excel spreadsheet'}</button></div><strong>Your budget isn’t saved online. Download a copy before leaving.</strong></section><div className="actions"><button className="secondary" onClick={()=>go(3)}>Back to revise</button><button className="text-button" onClick={()=>go(2)}>Try another choice</button></div></>}
 <footer><ShieldCheck size={18}/><span>No account. No online budget storage. All amounts in Canadian dollars.</span></footer></main></>;
}
